Fix consoledot index.html fetching in beta builds
Our webpack is fetching console.redhat.com top HTML file, which in turn
fetches insights-chrome (different versions for /beta/ vs /),
which then fetches our app.

https://console.redhat.com/apps/chrome returns HTML snippet as before but
https://console.redhat.com/beta/apps/chrome started giving JSON.
This resulted in axios auto-parsing `chromeTemplate` and:

    Error: Expected html to be a string but got [{"name":"chrome/",...

Appending /index.html returns HTML for both envs, fixing the build.

I think it's actually only used for serving locally `yarn start`,
and when serving static build to selenium/cypress.
When deployed users will get the central copy of index.html and not
our `build/openshift/index.html` copy.
Still, it broke the build in candidate deploy pipeline.

TODO: We could probably stop fetching it on build in favor of proxying?