NotFoundError: Use getAppBasename() to get the correct basename
I knew we had a helper for it, but I forgot where it is, so I thought
I misremembered. Turns out we did have a helper for this. So let's use
it.