./deploy_info.mjs: Better handle partial data
Currently a new 301 redirect we didn't follow is causing the script to
crash on `live_beta_master` env not having `src_hash`.
Similarly, we're crashing on any 404/500 fetching any app.info.json.

* `--json` mode was working, then crashing — no longer crashes.
* `--short` was crashing, now shows:

           origin/master 53683fd2d  [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
     build_pushed_master 53683fd2d  [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
             live_master    ### {"ERROR":" curl: (22) The requested URL returned error: 500\n","url":"https://qaprodauth.console.redhat.com/apps/openshift/app.info.json"}
build_pushed_beta_master 53683fd2d  [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
        live_beta_master    ### {"ERROR":"SyntaxError: JSON5: invalid character 'M' at 1:1","body":"Moved Permanently. Redirecting to /preview/apps/openshift/app.info.json","url":"https://qaprodauth.console.redhat.com/beta/apps/openshift/app.info.json"}
        origin/candidate 0566588bc  [openshift-assisted-ui-lib: 2.18.7]
  build_pushed_candidate 0566588bc  [openshift-assisted-ui-lib: 2.18.7]
          live_candidate 0566588bc  [openshift-assisted-ui-lib: 2.18.7]
           origin/stable b3df60f35  [openshift-assisted-ui-lib: 2.18.7]
     build_pushed_stable b3df60f35  [openshift-assisted-ui-lib: 2.18.7]
             live_stable b3df60f35  [openshift-assisted-ui-lib: 2.18.7]

* `--set-git-branches` was crashing, now shows:

#                             origin/master 53683fd2d    [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
git branch --force      build_pushed_master 53683fd2d  # [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
git branch -D                   live_master    ### MISSING INFO: {"ERROR":" curl: (22) The requested URL returned error: 500\n","url":"https://qaprodauth.console.redhat.com/apps/openshift/app.info.json"}
git branch --force build_pushed_beta_master 53683fd2d  # [@openshift-assisted/ui-lib: 2.19.6, @openshift-assisted/locales: 2.19.6]
git branch -D              live_beta_master    ### MISSING INFO: {"ERROR":"SyntaxError: JSON5: invalid character 'M' at 1:1","body":"Moved Permanently. Redirecting to /preview/apps/openshift/app.info.json","url":"https://qaprodauth.console.redhat.com/beta/apps/openshift/app.info.json"}
#                          origin/candidate 0566588bc    [openshift-assisted-ui-lib: 2.18.7]
git branch --force   build_pushed_candidate 0566588bc  # [openshift-assisted-ui-lib: 2.18.7]
git branch --force           live_candidate 0566588bc  # [openshift-assisted-ui-lib: 2.18.7]
#                             origin/stable b3df60f35    [openshift-assisted-ui-lib: 2.18.7]
git branch --force      build_pushed_stable b3df60f35  # [openshift-assisted-ui-lib: 2.18.7]
git branch --force              live_stable b3df60f35  # [openshift-assisted-ui-lib: 2.18.7]

* `--git-graph`: Since the above DELETES stale build_* or live_* branches,
  `git log` crashes with 'bad revision' error.  But, we print the
  git command which you're free to edit if you really want a partial graph.

fatal: bad revision 'live_beta_master'
Error: Command failed: env GIT_PAGER= git log origin/master build_pushed_master live_master build_pushed_beta_master live_beta_master origin/candidate build_pushed_candidate live_candidate origin/stable build_pushed_stable live_stable --not live_stable~2 --graph --extended-regexp --grep=[Mm]erge|[Cc]herry --pretty=%C(auto)%cs %H%d %C(dim)%s — %C(auto)%w(0,0,10)%b --color=always --
    at checkExecSyncError (node:child_process:885:11)
    ...