chore(deploy): Limit git fetch size with shallow clone
After the 2nd part of the deploy pipeline
https://insights-dev-jenkins.apps.crcd01ue1.zmsj.p1.openshiftapps.com/job/insights-frontend-deployer/job/uhc-portal-frontend-deploy/job/qa-beta/
(and /qa-stable) was broken for ~11 days (for unrelated credentials issue),
it has a problem doing `git fetch` of our builds — because the accumulated
history is so large:

remote: Enumerating objects: 31387, done.
...
remote: Counting objects: 100% (20764/20764), done.
...
remote: Compressing objects: 100% (9308/9308), done.
...
Receiving objects:  48% (15126/31387), 896.45 MiB | 2.69 MiB/s
error: git-remote-https died of signal 15
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

I'm told this is the right Jenkins syntax to do a shallow clone
(only last commit), hope it will help?